// front_end/src/app/CreateUser/page.tsx
"use client"

import { redirect } from "next/navigation";
import { useState } from "react";

export default function CreateUser() {
    const [username, setUsername] = useState<string>('');
    const [password, setPassword] = useState<string>('');
    const [msg, setMsg] = useState<string>('');
    const create = (e: Event) => {
        e.preventDefault();
        fetch('/auth/createuser', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                username: username,
                password: password,
            })
        })
            .then((res) => res.json())
            .then((result) => {
                if (result.result == "ok") {
                    redirect('/');
                } else {
                    setMsg("Error");
                }
            });
    }


    return (<>
        <div className="grid grid-rows-[20px_1fr_20px] items-cente
  r justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)]">
            <main className="flex flex-col gap-8 row-start-2 items-center sm:items-start">
                <h1>Create a new User</h1>
                <h3>{msg}</h3>
                <form onSubmit={create} >
                    <input type="text" placeholder="Name" className="input input-bordered w-full max-w-xs" value={username} onChange={(e) => setUsername(e.target.value)} />
                    <input type="password" placeholder="Password" className="input input-bordered w-full max-w-xs" value={password} onChange={(e) => setPassword(e.target.value)} />
                    <button className="btn" type="submit">Login</button>
                </form>
            </main >
        </div >
    </>
    );
}

// front_end/src/pages/CreateUser.svelte
<script lang="ts">
    import { push } from "svelte-spa-router";
    import { ENDPOINT_CREATE_USER } from "../js/endpoints.js";

    let username: string, password: string;

    async function handleCreate() {
        await fetch(ENDPOINT_CREATE_USER, {
            method: "POST",
            headers: {
                Accept: "application/json",
                "Content-Type": "application/json",
            },
            body: JSON.stringify({ username: username, password: password }),
            credentials: "include",
        });
        push("/");
    }
</script>

<div class="p-8 container mx-auto">
    <p class="text-6xl pb-4">Create User</p>
    <div class="grid lg:grid-cols-2 gap-4">
        <input
            class="input input-bordered input-primary"
            type="username"
            placeholder="Username"
            bind:value={username}
        />
        <input
            class="input input-bordered input-secondary pb-2"
            type="password"
            placeholder="Password"
            bind:value={password}
        />
        <button class="btn btn-primary lg:w-32 md:w-32" on:click={handleCreate}
            >Create User</button
        >
        <div class="lg:col-span-2">
            or <button
                type="submit"
                on:click={() => {
                    push("/createuser/");
                }}>Create a User</button
            >
        </div>
    </div>
</div>
